"""Initial schema: core tables, monthly partitions and event storage

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-12 20:03:07.398540
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from datetime import date

from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


PARTITIONED_TABLES = ("capture_events", "source_events", "audit_events")
#: Months created up-front so a fresh database can ingest immediately.
BOOTSTRAP_MONTHS = 4


def _month_bounds(offset: int) -> tuple[str, str]:
    """Return (start, end) ISO dates for the month ``offset`` months ahead."""
    today = date.today().replace(day=1)
    year, month = today.year, today.month + offset
    year += (month - 1) // 12
    month = (month - 1) % 12 + 1
    start = date(year, month, 1)
    end = date(year + 1, 1, 1) if month == 12 else date(year, month + 1, 1)
    return start.isoformat(), end.isoformat()


def _create_partitions() -> None:
    for table in PARTITIONED_TABLES:
        # DEFAULT partition first: a write can never fail for lack of a partition.
        op.execute(f"CREATE TABLE IF NOT EXISTS {table}_default PARTITION OF {table} DEFAULT")
        for offset in range(BOOTSTRAP_MONTHS):
            start, end = _month_bounds(offset)
            name = f"{table}_p{start[:4]}{start[5:7]}"
            op.execute(
                f"CREATE TABLE IF NOT EXISTS {name} PARTITION OF {table} "
                f"FOR VALUES FROM ('{start}') TO ('{end}')"
            )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('actor_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('admin_read', 'admin_search', 'export_created', 'export_downloaded', 'approval_changed', 'retention_soft_delete', 'retention_hard_delete', 'legal_hold_set', 'legal_hold_cleared', 'device_revoked', 'auth_login', 'auth_refresh', 'auth_denied', 'config_read', 'policy_blocked', 'attachment_presigned', 'attachment_finalized', name='audit_action', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('source_ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("outcome in ('success','failure','denied')", name=op.f('ck_audit_events_outcome_allowed')),
    sa.PrimaryKeyConstraint('id', 'created_at', name='pk_audit_events'),
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index('ix_audit_events_action', 'audit_events', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_events_actor', 'audit_events', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_audit_events_org_created', 'audit_events', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_audit_events_resource', 'audit_events', ['resource_type', 'resource_id'], unique=False)
    op.create_table('capture_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('conversation_upsert', 'message_version', 'attachment_metadata', 'feedback', 'diagnostic', 'compliance_event', name='capture_event_kind', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('accepted', 'duplicate', 'rejected', 'retryable', name='ingest_status', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('adapter_version', sa.String(length=32), nullable=True),
    sa.Column('extension_version', sa.String(length=32), nullable=True),
    sa.Column('client_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('payload_bytes', sa.Integer(), nullable=False),
    sa.Column('raw_s3_key', sa.Text(), nullable=True),
    sa.Column('raw_s3_version_id', sa.String(length=1024), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.CheckConstraint('payload_bytes >= 0', name=op.f('ck_capture_events_payload_bytes_non_negative')),
    sa.PrimaryKeyConstraint('id', 'created_at', name='pk_capture_events'),
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index('ix_capture_events_conversation', 'capture_events', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_capture_events_idempotency', 'capture_events', ['idempotency_key'], unique=False)
    op.create_index('ix_capture_events_org_created', 'capture_events', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_capture_events_unarchived', 'capture_events', ['archived_at', 'created_at'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('capture_event_id', sa.UUID(), nullable=False),
    sa.Column('capture_event_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('organization_id', 'idempotency_key', name='pk_idempotency_keys')
    )
    op.create_index('ix_idempotency_keys_created_at', 'idempotency_keys', ['created_at'], unique=False)
    op.create_table('jobs',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('archive_raw_event', 'build_conversation_snapshot', 'finalize_attachment', 'run_export', 'retention_sweep', 'compliance_sync', 'reconcile_partial', 'maintain_partitions', 'cleanup_stale', name='job_kind', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'dead', 'cancelled', name='job_status', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('lock_token', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_jobs_attempts_non_negative')),
    sa.CheckConstraint('max_attempts >= 1', name=op.f('ck_jobs_max_attempts_positive')),
    sa.CheckConstraint('priority BETWEEN 0 AND 1000', name=op.f('ck_jobs_priority_in_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_claim', 'jobs', ['status', 'run_after', 'priority', 'created_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index('ix_jobs_kind_status', 'jobs', ['kind', 'status'], unique=False)
    op.create_index('ix_jobs_stale_locks', 'jobs', ['locked_at'], unique=False, postgresql_where=sa.text("status = 'running'"))
    op.create_index('uq_jobs_dedupe_active', 'jobs', ['dedupe_key'], unique=True, postgresql_where=sa.text("dedupe_key IS NOT NULL AND status IN ('pending','running')"))
    op.create_table('organizations',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('primary_domain', sa.String(length=255), nullable=False),
    sa.Column('allowed_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(slug) > 0', name=op.f('ck_organizations_slug_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_index(op.f('ix_organizations_created_at'), 'organizations', ['created_at'], unique=False)
    op.create_index('ix_organizations_primary_domain', 'organizations', ['primary_domain'], unique=False)
    op.create_table('source_event_keys',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_event_id', sa.String(length=255), nullable=False),
    sa.Column('source_event_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('organization_id', 'source', 'source_event_id', name='pk_source_event_keys')
    )
    op.create_index('ix_source_event_keys_created_at', 'source_event_keys', ['created_at'], unique=False)
    op.create_table('source_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_event_id', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('conversation', 'message', 'file', 'deletion', 'unknown', name='source_event_kind', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('source_conversation_id', sa.String(length=255), nullable=True),
    sa.Column('source_message_id', sa.String(length=255), nullable=True),
    sa.Column('source_workspace_id', sa.String(length=255), nullable=True),
    sa.Column('actor_email_hash', sa.String(length=64), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deletion', sa.Boolean(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('raw_s3_key', sa.Text(), nullable=True),
    sa.Column('raw_s3_version_id', sa.String(length=1024), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', 'created_at', name='pk_source_events'),
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index('ix_source_events_conversation', 'source_events', ['source_conversation_id'], unique=False)
    op.create_index('ix_source_events_org_event_time', 'source_events', ['organization_id', 'event_time'], unique=False)
    op.create_index('ix_source_events_source_event_id', 'source_events', ['source', 'source_event_id'], unique=False)
    op.create_table('job_attempts',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=True),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('recovered_stale_lock', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_job_attempts_attempt_number_positive')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_attempts_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_attempts')),
    sa.UniqueConstraint('job_id', 'attempt_number', name='uq_job_attempts_job_number')
    )
    op.create_index('ix_job_attempts_started', 'job_attempts', ['started_at'], unique=False)
    op.create_table('retention_policies',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applies_to', sa.String(length=64), nullable=False),
    sa.Column('retain_days', sa.Integer(), nullable=False),
    sa.Column('grace_days', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('soft_delete', 'hard_delete', 'anonymize', name='retention_action', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('legal_hold_exempt', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("NOT (legal_hold_exempt = true AND action = 'hard_delete')", name=op.f('ck_retention_policies_legal_hold_exempt_cannot_hard_delete')),
    sa.CheckConstraint("applies_to in ('conversations','capture_events','source_events','audit_events','attachments','exports')", name=op.f('ck_retention_policies_applies_to_allowed')),
    sa.CheckConstraint('grace_days >= 0', name=op.f('ck_retention_policies_grace_days_non_negative')),
    sa.CheckConstraint('retain_days >= 1', name=op.f('ck_retention_policies_retain_days_positive')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_retention_policies_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_policies')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_retention_policies_org_name')
    )
    op.create_index(op.f('ix_retention_policies_created_at'), 'retention_policies', ['created_at'], unique=False)
    op.create_index('ix_retention_policies_default', 'retention_policies', ['organization_id', 'is_default'], unique=True, postgresql_where=sa.text('is_default = true'))
    op.create_table('sync_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('stream', sa.String(length=64), nullable=False),
    sa.Column('cursor_value', sa.Text(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_errors', sa.Integer(), nullable=False),
    sa.Column('total_events', sa.BigInteger(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('consecutive_errors >= 0', name=op.f('ck_sync_checkpoints_consecutive_errors_non_negative')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sync_checkpoints_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_checkpoints')),
    sa.UniqueConstraint('organization_id', 'source', 'stream', name='uq_sync_checkpoints_stream')
    )
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notice_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("position('@' in email) > 1", name=op.f('ck_users_email_looks_valid')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('organization_id', 'email', name='uq_users_org_email')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index('ix_users_email_hash', 'users', ['email_hash'], unique=False)
    op.create_table('workspaces',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('source_workspace_id', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('workspace_hash', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('managed_company', 'personal', 'unverified', name='workspace_kind', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capture_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind <> 'managed_company') OR (capture_enabled IS NOT NULL)", name=op.f('ck_workspaces_managed_requires_capture_flag')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_workspaces_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('organization_id', 'workspace_hash', name='uq_workspaces_org_hash')
    )
    op.create_index(op.f('ix_workspaces_created_at'), 'workspaces', ['created_at'], unique=False)
    op.create_index('ix_workspaces_source_workspace_id', 'workspaces', ['source_workspace_id'], unique=False)
    op.create_table('conversations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('source_conversation_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('model_slug', sa.String(length=128), nullable=True),
    sa.Column('capture_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capture_completeness', sa.Enum('complete_current_page', 'partial_scroll_limit', 'live_only', 'compliance_verified', 'reconciled', 'unknown', name='capture_completeness', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('employee_id_hash', sa.String(length=64), nullable=True),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('snapshot_s3_key', sa.Text(), nullable=True),
    sa.Column('snapshot_sha256', sa.String(length=64), nullable=True),
    sa.Column('snapshot_stale', sa.Boolean(), nullable=False),
    sa.Column('retention_policy_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_reason', sa.String(), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('NOT (legal_hold = true AND deleted_at IS NOT NULL)', name=op.f('ck_conversations_legal_hold_blocks_soft_delete')),
    sa.CheckConstraint('message_count >= 0', name=op.f('ck_conversations_message_count_non_negative')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_conversations_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retention_policy_id'], ['retention_policies.id'], name=op.f('fk_conversations_retention_policy_id_retention_policies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_conversations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'source_conversation_id', name='uq_conversations_org_workspace_source')
    )
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index('ix_conversations_legal_hold', 'conversations', ['legal_hold'], unique=False, postgresql_where=sa.text('legal_hold = true'))
    op.create_index('ix_conversations_snapshot_stale', 'conversations', ['snapshot_stale'], unique=False, postgresql_where=sa.text('snapshot_stale = true AND deleted_at IS NULL'))
    op.create_index('ix_conversations_user_updated', 'conversations', ['user_id', 'last_captured_at'], unique=False)
    op.create_index('ix_conversations_workspace_updated', 'conversations', ['workspace_id', 'source_updated_at'], unique=False)
    op.create_table('devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('extension_id', sa.String(length=64), nullable=True),
    sa.Column('extension_version', sa.String(length=32), nullable=True),
    sa.Column('adapter_version', sa.String(length=32), nullable=True),
    sa.Column('browser_version', sa.String(length=64), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('managed_by_policy', sa.Boolean(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_rotation_counter', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_devices_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('user_id', 'device_fingerprint', name='uq_devices_user_fingerprint')
    )
    op.create_index(op.f('ix_devices_created_at'), 'devices', ['created_at'], unique=False)
    op.create_index('ix_devices_org_last_seen', 'devices', ['organization_id', 'last_seen_at'], unique=False)
    op.create_index('ix_devices_refresh_token_hash', 'devices', ['refresh_token_hash'], unique=False)
    op.create_table('exports',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('curated_training_jsonl', 'compliance_extract', 'legal_hold_bundle', name='export_kind', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='export_status', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('split_strategy', sa.String(length=32), nullable=False),
    sa.Column('split_ratios', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('include_attachments', sa.Boolean(), nullable=False),
    sa.Column('conversation_count', sa.Integer(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('s3_prefix', sa.Text(), nullable=True),
    sa.Column('manifest_s3_key', sa.Text(), nullable=True),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=True),
    sa.Column('parts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("split_strategy in ('conversation_hash','none')", name=op.f('ck_exports_split_strategy_allowed')),
    sa.CheckConstraint('record_count >= 0', name=op.f('ck_exports_record_count_non_negative')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_exports_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_exports_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exports'))
    )
    op.create_index(op.f('ix_exports_created_at'), 'exports', ['created_at'], unique=False)
    op.create_index('ix_exports_org_status', 'exports', ['organization_id', 'status'], unique=False)
    op.create_table('legal_holds',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('matter_reference', sa.String(length=255), nullable=True),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_legal_holds_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_legal_holds_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['released_by_user_id'], ['users.id'], name=op.f('fk_legal_holds_released_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_holds')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_legal_holds_org_name')
    )
    op.create_index('ix_legal_holds_active', 'legal_holds', ['organization_id'], unique=False, postgresql_where=sa.text('released_at IS NULL'))
    op.create_index(op.f('ix_legal_holds_created_at'), 'legal_holds', ['created_at'], unique=False)
    op.create_table('user_identities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('hosted_domain', sa.String(length=255), nullable=True),
    sa.Column('last_authenticated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_identities')),
    sa.UniqueConstraint('issuer', 'subject', name='uq_user_identities_issuer_subject')
    )
    op.create_index(op.f('ix_user_identities_created_at'), 'user_identities', ['created_at'], unique=False)
    op.create_index('ix_user_identities_user_id', 'user_identities', ['user_id'], unique=False)
    op.create_table('attachments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('client_attachment_id', sa.String(length=128), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('safe_filename', sa.String(length=255), nullable=False),
    sa.Column('declared_mime_type', sa.String(length=255), nullable=True),
    sa.Column('detected_mime_type', sa.String(length=255), nullable=True),
    sa.Column('extension', sa.String(length=32), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('verified_byte_size', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('verified_sha256', sa.String(length=64), nullable=True),
    sa.Column('state', sa.Enum('pending', 'quarantine', 'clean', 'rejected', 'expired', 'metadata_only', name='attachment_state', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('metadata_only', sa.Boolean(), nullable=False),
    sa.Column('source_file_id', sa.String(length=255), nullable=True),
    sa.Column('quarantine_s3_key', sa.Text(), nullable=True),
    sa.Column('clean_s3_key', sa.Text(), nullable=True),
    sa.Column('curated_s3_key', sa.Text(), nullable=True),
    sa.Column('s3_version_id', sa.String(length=1024), nullable=True),
    sa.Column('presign_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('presign_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_status', sa.String(length=32), nullable=True),
    sa.Column('scan_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exif_stripped', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_reason', sa.String(), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("state <> 'clean' OR clean_s3_key IS NOT NULL OR metadata_only = true", name=op.f('ck_attachments_clean_requires_key')),
    sa.CheckConstraint('byte_size >= 0', name=op.f('ck_attachments_byte_size_non_negative')),
    sa.CheckConstraint('char_length(sha256) = 64', name=op.f('ck_attachments_sha256_is_hex64')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_attachments_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_attachments_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_attachments_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attachments_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_attachments_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments')),
    sa.UniqueConstraint('conversation_id', 'client_attachment_id', name='uq_attachments_conversation_client_id')
    )
    op.create_index(op.f('ix_attachments_created_at'), 'attachments', ['created_at'], unique=False)
    op.create_index('ix_attachments_org_sha', 'attachments', ['organization_id', 'sha256'], unique=False)
    op.create_index('ix_attachments_pending_expiry', 'attachments', ['presign_expires_at'], unique=False, postgresql_where=sa.text("state = 'pending'"))
    op.create_index('ix_attachments_state_created', 'attachments', ['state', 'created_at'], unique=False)
    op.create_table('conversation_branches',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('parent_branch_id', sa.UUID(), nullable=True),
    sa.Column('source_branch_id', sa.String(length=255), nullable=True),
    sa.Column('branch_key', sa.String(length=64), nullable=False),
    sa.Column('branch_index', sa.Integer(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_branches_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_branch_id'], ['conversation_branches.id'], name=op.f('fk_conversation_branches_parent_branch_id_conversation_branches'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_branches')),
    sa.UniqueConstraint('conversation_id', 'branch_key', name='uq_branches_conversation_key')
    )
    op.create_index('ix_branches_conversation_selected', 'conversation_branches', ['conversation_id', 'is_selected'], unique=False)
    op.create_index(op.f('ix_conversation_branches_created_at'), 'conversation_branches', ['created_at'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('parent_message_id', sa.UUID(), nullable=True),
    sa.Column('source_message_id', sa.String(length=255), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'tool', 'system', name='message_role', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('author_name', sa.String(length=128), nullable=True),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('version_count', sa.Integer(), nullable=False),
    sa.Column('completion_status', sa.Enum('complete', 'partial', 'reconciled', 'unknown', name='completion_status', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_reason', sa.String(), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('NOT (legal_hold = true AND deleted_at IS NOT NULL)', name=op.f('ck_messages_legal_hold_blocks_soft_delete')),
    sa.CheckConstraint('sequence_index >= 0', name=op.f('ck_messages_sequence_index_non_negative')),
    sa.CheckConstraint('version_count >= 0', name=op.f('ck_messages_version_count_non_negative')),
    sa.ForeignKeyConstraint(['branch_id'], ['conversation_branches.id'], name=op.f('fk_messages_branch_id_conversation_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_messages_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.id'], name=op.f('fk_messages_parent_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('conversation_id', 'fingerprint', name='uq_messages_conversation_fp')
    )
    op.create_index('ix_messages_conversation_sequence', 'messages', ['conversation_id', 'sequence_index'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_org_created', 'messages', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_messages_partial_completion', 'messages', ['completion_status'], unique=False, postgresql_where=sa.text("completion_status = 'partial'"))
    op.create_index('uq_messages_conversation_source_id', 'messages', ['conversation_id', 'source_message_id'], unique=True, postgresql_where=sa.text('source_message_id IS NOT NULL'))
    op.create_table('message_versions',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_edit', sa.Boolean(), nullable=False),
    sa.Column('is_regeneration', sa.Boolean(), nullable=False),
    sa.Column('completion_status', sa.Enum('complete', 'partial', 'reconciled', 'unknown', name='completion_status', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('plain_text', sa.Text(), nullable=False),
    sa.Column('sanitized_html', sa.Text(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('normalized_sha256', sa.String(length=64), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capture_source', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('capture_event_id', sa.UUID(), nullable=True),
    sa.Column('raw_s3_key', sa.Text(), nullable=True),
    sa.Column('raw_s3_version_id', sa.String(length=1024), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_reason', sa.String(), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('char_count >= 0', name=op.f('ck_message_versions_char_count_non_negative')),
    sa.CheckConstraint('version_number >= 1', name=op.f('ck_message_versions_version_number_positive')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_message_versions_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_message_versions_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_versions_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_message_versions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_versions')),
    sa.UniqueConstraint('message_id', 'normalized_sha256', name='uq_message_versions_message_content'),
    sa.UniqueConstraint('message_id', 'version_number', name='uq_message_versions_message_number')
    )
    op.create_index('ix_message_versions_conv_norm', 'message_versions', ['conversation_id', 'normalized_sha256'], unique=False)
    op.create_index('ix_message_versions_conversation', 'message_versions', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_message_versions_created_at'), 'message_versions', ['created_at'], unique=False)
    op.create_index('ix_message_versions_org_captured', 'message_versions', ['organization_id', 'captured_at'], unique=False)
    op.create_table('training_approvals',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'withdrawn', name='approval_status', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('contains_secrets', sa.Boolean(), nullable=False),
    sa.Column('contains_personal_data', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_training_approvals_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_training_approvals_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_training_approvals_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_training_approvals_reviewed_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_approvals')),
    sa.UniqueConstraint('conversation_id', 'message_id', name='uq_training_approvals_conversation_message')
    )
    op.create_index('ix_training_approvals_approved', 'training_approvals', ['organization_id', 'status'], unique=False, postgresql_where=sa.text("status = 'approved'"))
    op.create_index(op.f('ix_training_approvals_created_at'), 'training_approvals', ['created_at'], unique=False)
    op.create_table('feedback',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('message_version_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('useful', 'incorrect', 'approved', 'rejected', 'note', name='feedback_kind', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('client_feedback_id', sa.String(length=128), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR rating BETWEEN 1 AND 5', name=op.f('ck_feedback_rating_in_range')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_feedback_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_feedback_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_version_id'], ['message_versions.id'], name=op.f('fk_feedback_message_version_id_message_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_feedback_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedback_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback')),
    sa.UniqueConstraint('organization_id', 'client_feedback_id', name='uq_feedback_org_client_id')
    )
    op.create_index('ix_feedback_conversation', 'feedback', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index('ix_feedback_message', 'feedback', ['message_id'], unique=False)
    op.create_table('message_attachments',
    sa.Column('attachment_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('message_version_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relation in ('uploaded_by_user','generated_by_assistant','referenced_historical')", name=op.f('ck_message_attachments_relation_allowed')),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], name=op.f('fk_message_attachments_attachment_id_attachments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_message_attachments_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_attachments_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_version_id'], ['message_versions.id'], name=op.f('fk_message_attachments_message_version_id_message_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_attachments')),
    sa.UniqueConstraint('attachment_id', 'message_id', name='uq_message_attachments_pair')
    )
    op.create_index('ix_message_attachments_conversation', 'message_attachments', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_attachments_created_at'), 'message_attachments', ['created_at'], unique=False)
    op.create_index('ix_message_attachments_message', 'message_attachments', ['message_id'], unique=False)
    op.create_table('message_parts',
    sa.Column('message_version_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('part_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('text', 'code', 'heading', 'list', 'table', 'quote', 'link', 'citation', 'image_ref', 'attachment_ref', 'tool_output', 'unknown', name='part_kind', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('structured', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('part_index >= 0', name=op.f('ck_message_parts_part_index_non_negative')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_message_parts_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_version_id'], ['message_versions.id'], name=op.f('fk_message_parts_message_version_id_message_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_parts')),
    sa.UniqueConstraint('message_version_id', 'part_index', name='uq_message_parts_version_index')
    )
    op.create_index('ix_message_parts_kind', 'message_parts', ['kind'], unique=False)
    _create_partitions()

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_parts_kind', table_name='message_parts')
    op.drop_table('message_parts')
    op.drop_index('ix_message_attachments_message', table_name='message_attachments')
    op.drop_index(op.f('ix_message_attachments_created_at'), table_name='message_attachments')
    op.drop_index('ix_message_attachments_conversation', table_name='message_attachments')
    op.drop_table('message_attachments')
    op.drop_index('ix_feedback_message', table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_index('ix_feedback_conversation', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_training_approvals_created_at'), table_name='training_approvals')
    op.drop_index('ix_training_approvals_approved', table_name='training_approvals', postgresql_where=sa.text("status = 'approved'"))
    op.drop_table('training_approvals')
    op.drop_index('ix_message_versions_org_captured', table_name='message_versions')
    op.drop_index(op.f('ix_message_versions_created_at'), table_name='message_versions')
    op.drop_index('ix_message_versions_conversation', table_name='message_versions')
    op.drop_index('ix_message_versions_conv_norm', table_name='message_versions')
    op.drop_table('message_versions')
    op.drop_index('uq_messages_conversation_source_id', table_name='messages', postgresql_where=sa.text('source_message_id IS NOT NULL'))
    op.drop_index('ix_messages_partial_completion', table_name='messages', postgresql_where=sa.text("completion_status = 'partial'"))
    op.drop_index('ix_messages_org_created', table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index('ix_messages_conversation_sequence', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversation_branches_created_at'), table_name='conversation_branches')
    op.drop_index('ix_branches_conversation_selected', table_name='conversation_branches')
    op.drop_table('conversation_branches')
    op.drop_index('ix_attachments_state_created', table_name='attachments')
    op.drop_index('ix_attachments_pending_expiry', table_name='attachments', postgresql_where=sa.text("state = 'pending'"))
    op.drop_index('ix_attachments_org_sha', table_name='attachments')
    op.drop_index(op.f('ix_attachments_created_at'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('ix_user_identities_user_id', table_name='user_identities')
    op.drop_index(op.f('ix_user_identities_created_at'), table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index(op.f('ix_legal_holds_created_at'), table_name='legal_holds')
    op.drop_index('ix_legal_holds_active', table_name='legal_holds', postgresql_where=sa.text('released_at IS NULL'))
    op.drop_table('legal_holds')
    op.drop_index('ix_exports_org_status', table_name='exports')
    op.drop_index(op.f('ix_exports_created_at'), table_name='exports')
    op.drop_table('exports')
    op.drop_index('ix_devices_refresh_token_hash', table_name='devices')
    op.drop_index('ix_devices_org_last_seen', table_name='devices')
    op.drop_index(op.f('ix_devices_created_at'), table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_conversations_workspace_updated', table_name='conversations')
    op.drop_index('ix_conversations_user_updated', table_name='conversations')
    op.drop_index('ix_conversations_snapshot_stale', table_name='conversations', postgresql_where=sa.text('snapshot_stale = true AND deleted_at IS NULL'))
    op.drop_index('ix_conversations_legal_hold', table_name='conversations', postgresql_where=sa.text('legal_hold = true'))
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_workspaces_source_workspace_id', table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_created_at'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('ix_users_email_hash', table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('sync_checkpoints')
    op.drop_index('ix_retention_policies_default', table_name='retention_policies', postgresql_where=sa.text('is_default = true'))
    op.drop_index(op.f('ix_retention_policies_created_at'), table_name='retention_policies')
    op.drop_table('retention_policies')
    op.drop_index('ix_job_attempts_started', table_name='job_attempts')
    op.drop_table('job_attempts')
    op.drop_index('ix_source_events_source_event_id', table_name='source_events')
    op.drop_index('ix_source_events_org_event_time', table_name='source_events')
    op.drop_index('ix_source_events_conversation', table_name='source_events')
    op.drop_table('source_events')
    op.drop_index('ix_source_event_keys_created_at', table_name='source_event_keys')
    op.drop_table('source_event_keys')
    op.drop_index('ix_organizations_primary_domain', table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('uq_jobs_dedupe_active', table_name='jobs', postgresql_where=sa.text("dedupe_key IS NOT NULL AND status IN ('pending','running')"))
    op.drop_index('ix_jobs_stale_locks', table_name='jobs', postgresql_where=sa.text("status = 'running'"))
    op.drop_index('ix_jobs_kind_status', table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index('ix_jobs_claim', table_name='jobs', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('jobs')
    op.drop_index('ix_idempotency_keys_created_at', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_capture_events_unarchived', table_name='capture_events')
    op.drop_index('ix_capture_events_org_created', table_name='capture_events')
    op.drop_index('ix_capture_events_idempotency', table_name='capture_events')
    op.drop_index('ix_capture_events_conversation', table_name='capture_events')
    op.drop_table('capture_events')
    op.drop_index('ix_audit_events_resource', table_name='audit_events')
    op.drop_index('ix_audit_events_org_created', table_name='audit_events')
    op.drop_index('ix_audit_events_actor', table_name='audit_events')
    op.drop_index('ix_audit_events_action', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
